### ISSUE TITLE
Feature Request: Allow users to change the position of the avatar

### ISSUE THREAD

**Issue by OhNo2** [LuckFire/RevampedUserArea#10]
You write on the repo that you can't use any themes/plugins that modify the user area. Would it be possible to make is so that you can move the icon to different parts of the screen?

I love the way that it works, but I also use "Horizontal Server List", which makes me unable to utilize this plugin. Other plugins offer settings similar to this that perform similar appearance modifications

**Comment by LuckFire** [comment]
Depends on what you exactly mean by "changing the position of the avatar", as some positioning stuff is [determined by OS type](https://github.com/Discord-Theme-Addons/compact-userarea/blob/main/src/theme/_os.scss).

You could probably make your own snippet that changes the positioning of stuff for you specifically.
