### ISSUE TITLE
Incompatibility with Horizontal Server List

### ISSUE THREAD

**Issue by lilynet336** [LuckFire/RevampedUserArea#11]
## **Describe the Issue**
When used together with Horizontal Server List theme, a few of the icons to the far left can't be clicked. It seems like the issue is only the ones under the User Area popout, except it also happens when the popout is not shown. 

### **OS Version**
macOS 11.5.1, also occurs on 12.0

### **Additional context**
- [x] I made sure I checked all of the known [issues](https://github.com/LuckFire/RevampedUserArea#issues) before submitting this report.

**Comment by LuckFire** [comment]
There is most likely not much I can do sadly to add support for it, you'd have to make some custom css to make it work for your specific scenario.

**Comment by lilynet336** [comment]
I noticed the other day that happens even without any other themes, you cannot click anything underneath the area of the popup even when it's not visible. This seems like a bug with specifically this theme. Is there anything I could do about that? Thank you.

**Comment by LuckFire** [comment]
Do you have any quick css that may be messing with the user area or guild list?

**Comment by lilynet336** [comment]
I wrote some CSS to make the channels sidebar smaller, I will remove that temporarily and see.

**Comment by lilynet336** [comment]
For some reason, the theme won't visibly work at all. I'll wait a bit and try again.

**Comment by LuckFire** [comment]
~~What client mod are you using?~~ I'm assuming you're using BetterDiscord? Also, you'll have to redownload from https://raw.githubusercontent.com/discord-extensions/compact-userarea/main/support/CompactUserarea.theme.css as I have made a few changes to the repo

**Comment by lilynet336** [comment]
Yes, I use BetterDiscord. I will redownload and let you know.

**Comment by lilynet336** [comment]
It still would not work, I got the `compiled.css` and pasted it into the file and it worked. The issue does still occur without any additional CSS or themes.

**Comment by LuckFire** [comment]
Interesting.. it may be a mac only issue as I haven't really *properly* tested it on macOS, all I have done was emulate a macOS version of Discord. I'll look into it more later.

**Comment by lilynet336** [comment]
Alright, thank you. I will also test in a Windows VM and see if it occurs there too.

**Comment by LuckFire** [comment]
If it occurs on Windows it may just be dependent on the Discord build. I have no issues with the theme on Windows, but I am using Discord Canary.

**Comment by lilynet336** [comment]
It does in fact happen on Windows too, but you're right that it could be my build. Notice how if you hover over the popout for the mute button etc, then try to mouse over whatever is under it, you cannot click in that area? For me that is half of the Friends button on macOS, and on Windows is most of the search bar. May still not occur for you though.

**Comment by LuckFire** [comment]
Can you take a video of the issue you're encountering so I have a better idea?

**Comment by lilynet336** [comment]
Here is what's going on with the macOS version, will boot to Windows and take one there too.

https://user-images.githubusercontent.com/61990607/162344812-0824ef27-8422-4d4b-b776-85a006688efa.mov

**Comment by lilynet336** [comment]
Obviously this isn't a breaking issue, but on Windows the search bar is about 95% obscured, which is a bit more serious.

**Comment by LuckFire** [comment]
OH. Yeah I have yet to find an fix for that issue yet.. it's also very weird cause sometimes it just fixes itself so I'm not sure how to properly tackle it.. I'll try looking into it more later, I know why it occurs but I have yet to think of a way to properly fix it.

**Comment by lilynet336** [comment]
Alright, thank you for the time and the discussion. I am decent at HTML and CSS but I wouldn’t have any knowledge of how to fix that either. I can look into it a little in my spare time, but as the theme creator would probably have more luck than me. Thanks again!

**Comment by LuckFire** [comment]
It happens because of z-indexing is all I know, I attempted to make it change the z-index depending on hovering but it doesn't really work as well as I thought I did.. probably just overall am doing something wrong.

**Comment by lilynet336** [comment]
Thank you for the info, I will experiment at some point and if I have success I will make a PR.

**Comment by LuckFire** [comment]
Awesome, appreciate it.

**Comment by lilynet336** [comment]
I believe I have fixed it, but I need to make sure that it works on Windows, and also doesn’t break anything else. I will test tomorrow and (hopefully) submit a PR.
