### ISSUE TITLE
Bug if used with Lavender theme

### ISSUE THREAD

**Issue by hades3729** [LuckFire/RevampedUserArea#13]
With Lavender, the profile picture in the bottom left disappear and I cannot access to anything

**Comment by LuckFire** [comment]
That theme messes with the userarea, so it isn't compatible with that theme. There isn't really much I can do since it's conflicting CSS, all I can recommend is you modify some of the CSS to your liking.

**Comment by kritishd8** [comment]
removing the import of `userActions.css` from the theme file should fix this.

(*To remove imports in lavender you need to be using `lavenderPlus.theme.css` version of the theme or dev version)
