### ISSUE TITLE
Overlay doesn't have priority over searchBarComponent and overlaps a little

### ISSUE THREAD

**Issue by brian6932** [LuckFire/RevampedUserArea#5]
This happens without any themes installed and regardless of  the state Normalize Classes setting:
![image](https://user-images.githubusercontent.com/18603393/113092897-e06c3880-91bc-11eb-9eae-abe63f6071aa.png)

Doesn't work well with themes installed either. The hover UI isn't prioritized, so you can't actually click any of the icons ([Material Discord](https://github.com/CapnKitten/BetterDiscord)):
![image](https://user-images.githubusercontent.com/18603393/113093477-ff1eff00-91bd-11eb-85f5-1690e6a539c4.png)
![bug](https://user-images.githubusercontent.com/18603393/113093919-cf242b80-91be-11eb-8cc8-0863fb6aaf49.gif)

Using BetterDiscord:
Stable 81005 (8bae9df)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit

**Comment by LuckFire** [comment]
this should(?) be fixed? reopen this issue if it isn't, havent tested it myself.

**Comment by brian6932** [comment]
yea it works, nice

**Comment by LuckFire** [comment]
epic
