### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by randomdiscorduser** [LuckFire/RevampedUserArea#6]
## **Describe the Issue**
When used with [Frosted Glass](https://github.com/DiscordStyles/FrostedGlass), the top avatar is misplaced.
[PowerClock](https://github.com/BenSegal855/powerclock) may be contributing to the issue as well.

### **OS Version**
![Screen Shot 2021-04-03 at 4 59 44 AM](https://user-images.githubusercontent.com/81717531/113457205-d6248700-93d4-11eb-8df7-9a6ced9ccb64.png)

### **Screenshots**
(The white box is not part of the issue, I added that to conceal my identity)

![Screen Shot 2021-04-03 at 5 04 01 AM](https://user-images.githubusercontent.com/81717531/113457627-e2f5aa80-93d5-11eb-954f-bcdf848c75ec.png)

### **Additional context**
- [x] I made sure I checked all of the known [issues](https://github.com/LuckFire/RevampedUserArea#issues) before submitting this report.

**Comment by LuckFire** [comment]
checked it out, this issue 100% isn't to do with powerclock.
what i could try doing is making some custom css that enables better support.
