### ISSUE TITLE
Discoloration + Overlapping

### ISSUE THREAD

**Issue by brian6932** [LuckFire/RevampedUserArea#7]
## **Describe the Issue**
Newest update has discoloration with the server sidebar and overlaps ontop of itself, when used with custom themes, works fine by itself though

### **OS Version**
BetterDiscord 1.1.1 on Windows

### **Screenshots**
![image](https://user-images.githubusercontent.com/18603393/119275022-c78e6b00-bbe0-11eb-95a0-64c0a7ac539d.png)

### **Additional context**
- [x] I made sure I checked all of the known [issues](https://github.com/LuckFire/RevampedUserArea#issues) before submitting this report.
Theme used: https://github.com/CapnKitten/Material-Discord/
--server-color = #232327

**Comment by LuckFire** [comment]
i think i've fixed this for the most part, however it'll still probably be somewhat broken. i can't really do much about that sadly since the theme appears to mess with the guild list.

**Comment by LuckFire** [comment]
nvm, i figured out it was cause it changes the height of the userarea. i've pushed a fix for this.

it appears the status picker also is somewhat broken, but there's actually not much i can do about that one.
