### ISSUE TITLE
Message form cannot expand into freed up space.

### ISSUE THREAD

**Issue by ditsuke** [LuckFire/RevampedUserArea#8]
## **Describe the Issue**
When using a plugin like HideChannels, the message form does not currently expand into the horizontal space freed up by compact-userarea. This is particularly awkward when the Discord window is too narrow to allow for any meaningful amount of text to fit into a line of the message box.

### **OS Version**
This issue affects all operating systems including the web version.

### **Proposed fix**
Compact User Area should unset the left-margin retained by the message form so that it can take advantage of the freed up horizontal space. 
I can open a PR if someone can help me figure out what file I should add the changes to. For my own use I've added the them to the `CompactUserarea.theme.css` file.

### **Screenshots**
Current:
![image](https://user-images.githubusercontent.com/72784348/120099918-b226bd00-c15b-11eb-857b-ab7efb6c0b40.png)
Suggested fix:
![image](https://user-images.githubusercontent.com/72784348/120099921-b652da80-c15b-11eb-95fc-c8d74ceeb0bb.png)

### **Additional context**
- [x] I made sure I checked all of the known [issues](https://github.com/LuckFire/RevampedUserArea#issues) before submitting this report.

**Comment by LuckFire** [comment]
can you link me the plugin that causes this issue?
